Plug 1.0 Upgrade - Runtime Setup
cennznet/cennznet pull request #68
Opened 2019-11-04 00:45 UTC by elim0322

Used [plug/node-template](https://github.com/plugblockchain/plug-blockchain/tree/develop/node-template) as reference, instead of [plug/node](https://github.com/plugblockchain/plug-blockchain/tree/develop/node) which has more business logic (not relevant to us)

Closes #66

2019-11-04 01:25 UTC, jordy25519 requested changes
This is right on track 👍 
Main changes required
- Must use babe not aura (part of the reason for upgrade)
- Must keep staking module

2019-11-04 01:25 UTC, holygits commented on src/service.rs
> +use aura_primitives::sr25519::AuthorityPair as AuraPair;
Will need to rectify this with `plug/node` to use babe instead

2019-11-04 01:25 UTC, holygits commented on runtime/src/lib.rs
> +use aura_primitives::sr25519::AuthorityId as AuraId;
Must use `babe` instead of `aura`

2019-11-04 01:25 UTC, holygits commented on runtime/src/lib.rs
> +	spec_version: 25,
Bump to `26`

2019-11-04 01:25 UTC, holygits commented on runtime/src/lib.rs
> +		Aura: aura::{Module, Config<T>, Inherent(Timestamp)},
Babe

2019-11-04 01:25 UTC, holygits commented on runtime/src/lib.rs
> -		Staking: staking::{default, OfflineWorker},
Need to keep staking also

2019-11-04 03:52 UTC, holygits commented on runtime/src/lib.rs
> +	spec_version: 25,
bump to `impl_version: 26` also 👌

2019-11-06 22:36 UTC, jordy25519 requested changes
GJ on this, needs some small changes

2019-11-06 22:36 UTC, holygits commented on Cargo.toml
> +travis-ci = { repository = "cennznet/cennznet", branch = "develop" }
need to change to circleci

2019-11-06 22:36 UTC, holygits commented on runtime/src/lib.rs
> +	impl_name: create_runtime_str!("plug-node"),
cennznet-node

2019-11-06 22:36 UTC, holygits commented on runtime/src/lib.rs
> +//! The Substrate runtime. This can be compiled with ``#[no_std]`, ready for Wasm.
The CENNZnet runtime.

2019-11-06 22:36 UTC, holygits commented on cli/src/chain_spec.rs
> +pub fn flaming_fir_config() -> Result<ChainSpec, String> {
Can remove all references to `flaming_fir`, CENNZnet doesn't need it

2019-11-06 22:36 UTC, holygits commented on Cargo.toml
> +	# "rpc",
Can add these crates in to this PR

2019-11-06 22:37 UTC, holygits commented on cli/src/chain_spec.rs
> +pub fn flaming_fir_config() -> Result<ChainSpec, String> {
I'll open a task to do this in Plug also

2019-11-06 22:44 UTC, elim0322 commented on runtime/src/lib.rs
> +	impl_name: create_runtime_str!("plug-node"),
My bad, I'll change it to this:
```rust
pub const VERSION: RuntimeVersion = RuntimeVersion {
	spec_name: create_runtime_str!("cennznet"),
	impl_name: create_runtime_str!("centrality-cennznet"),
	authoring_version: 1,
	spec_version: 26,
	impl_version: 26,
	apis: RUNTIME_API_VERSIONS,
};
```

2019-11-07 01:08 UTC, jordy25519 requested changes
LGTM! 🏅 🏅 🏅

2019-11-07 01:08 UTC, jordy25519 approved these changes

2019-11-07 01:11 UTC, merged