Migrate Sylo from master to develop
cennznet/cennznet pull request #83
Opened 2019-11-20 04:29 UTC by alexsednz

Closes #79

2019-11-20 04:42 UTC, jordy25519 approved these changes
Nice one. LGTM assuming CI passes

2019-11-20 06:02 UTC, cowboy-bebug requested changes
Nice! Some changes are required 👍

2019-11-20 06:02 UTC, cowboy-bebug commented on crml/sylo/Cargo.toml
> +version = "0.1.0"
Could u bump up the version to `version = "1.0.0"` <- this is what I have been using for all the modules 😄

2019-11-20 06:02 UTC, cowboy-bebug commented on crml/sylo/src/e2ee.rs
> +	use runtime_io::with_externalities;
This line is no longer required as we will use `execute_with()` instead.
(note: `with_externalities()` is moved to `substrate-externalities` crate)

2019-11-20 06:02 UTC, cowboy-bebug commented on crml/sylo/src/mock.rs
> +pub fn new_test_ext() -> sr_io::TestExternalities<Blake2Hasher> {
`TestExternalities` doesn't need a type anymore. Try:
```rust
pub fn new_test_ext() -> sr_io::TestExternalities {
```

2019-11-20 06:02 UTC, cowboy-bebug commented on crml/sylo/src/mock.rs
> +	system::GenesisConfig::<Test>::default()
`system:: GenesisConfig` doesn't need a type anymore. Try:
```rust
	system::GenesisConfig::default()
```

2019-11-20 06:02 UTC, elim0322 commented on crml/sylo/src/e2ee.rs
> +		with_externalities(&mut new_test_ext(), || {
Try `new_test_ext().execute_with(|| {`

2019-11-24 22:18 UTC, alexsednz commented on crml/sylo/src/e2ee.rs
> +		with_externalities(&mut new_test_ext(), || {
Done

2019-11-24 22:19 UTC, alexsednz commented on crml/sylo/src/mock.rs
> +	system::GenesisConfig::<Test>::default()
Done

2019-11-24 22:19 UTC, alexsednz commented on crml/sylo/src/mock.rs
> +pub fn new_test_ext() -> sr_io::TestExternalities<Blake2Hasher> {
Done

2019-11-24 22:19 UTC, alexsednz commented on crml/sylo/src/e2ee.rs
> +	use runtime_io::with_externalities;
Done

2019-11-24 22:19 UTC, alexsednz commented on crml/sylo/Cargo.toml
> +version = "0.1.0"
Done

2019-11-26 04:19 UTC, cowboy-bebug reviewed
To make build pass,
- remove all `use runtime_io::with_externalities;`
- replace all `with_externalities()` with `execute_with()`
- replace all `use mock;` ->  `use crate::mock;`

2019-11-27 18:30 UTC, cowboy-bebug approved these changes
Nice work! 🎉
Got some conflicts to resolve below

2019-11-27 23:21 UTC, merged