Issue/89 restore config
cennznet/cennznet pull request #97
Opened 2019-12-10 02:56 UTC by HaoZhaiX

- support `dev`, `kauri` and `rimu` genesis config

2019-12-11 22:03 UTC, cowboy-bebug reviewed
Do we want `genesis.json` configs instead of hardcoding them in scripts?

2019-12-11 23:32 UTC, jordy25519 requested changes
Looks good, small things like some doc comments need fixing.

Please generate the json blobs for kauri and rimu. Into a `genesis/` folder or similar should do
e.g.
1) `./target/release/cennznet build-spec --chain=kauri > kauri.json`
2) `./target/release/cennznet build-spec --chain kauri.json --raw > kauri.raw.json`

(Useful link: https://substrate.dev/docs/en/tutorials/start-a-private-network-with-substrate#creating-the-chainspec)

We can fix the Rimu keys in a follow up PR

---

**Update**: Don't need to upload the readable json

2019-12-11 23:32 UTC, holygits commented on cli/src/chain_spec/mod.rs
> +			// create_asset_stake: 1000, // removed upstream
We can safely remove this

2019-12-11 23:32 UTC, holygits commented on cli/src/chain_spec/dev.rs
> +/// kauri genesis config
`//! Dev genesis config`

2019-12-11 23:32 UTC, holygits commented on cli/src/chain_spec/dev.rs
> +use super::{config_genesis, get_account_id_from_seed, get_authority_keys_from_seed, ChainSpec, NetworkKeys};
Don't forget to add license header

2019-12-11 23:32 UTC, holygits commented on cli/src/chain_spec/rimu.rs
> +/// rimu genesis config
For module comment should do this: `//! Rimu genesis config`

2019-12-11 23:32 UTC, holygits commented on cli/src/lib.rs
> +	/// The CENNZnet Rumi testnet.
Rumi -> Rimu

2019-12-15 22:13 UTC, jordy25519 approved these changes
LGTM, needs fix for merge conflicts though

2019-12-15 23:05 UTC, merged